from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

def create_invoice_pdf(invoice):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    width, height = A4

    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(50, height - 60, "VendorBridge ERP Invoice")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 100, f"Invoice No: {invoice['invoice_number']}")
    pdf.drawString(50, height - 120, f"PO Number: {invoice['po_number']}")
    pdf.drawString(50, height - 140, f"Vendor: {invoice['vendor_name']}")
    pdf.drawString(50, height - 160, f"Date: {invoice['created_at']}")

    pdf.line(50, height - 190, 550, height - 190)

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 230, "Description")
    pdf.drawString(350, height - 230, "Amount")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 260, "Procurement Order")
    pdf.drawString(350, height - 260, f"Rs. {invoice['amount']}")

    pdf.drawString(50, height - 290, "GST 18%")
    pdf.drawString(350, height - 290, f"Rs. {invoice['tax']}")

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 330, "Grand Total")
    pdf.drawString(350, height - 330, f"Rs. {invoice['grand_total']}")

    pdf.line(50, height - 370, 550, height - 370)

    pdf.setFont("Helvetica", 11)
    pdf.drawString(50, height - 410, "Generated by VendorBridge Procurement ERP")
    pdf.drawString(50, height - 430, "Thank you for using VendorBridge.")

    pdf.save()
    buffer.seek(0)
    return buffer