import { useEffect, useState } from "react";
import API from "../services/api";
import { motion } from "framer-motion";
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import {
  FaChartLine,
  FaUsers,
  FaFileInvoice,
  FaRupeeSign,
  FaDownload,
} from "react-icons/fa";

function Reports() {
  const [stats, setStats] = useState(null);
  const [vendors, setVendors] = useState([]);
  const [rfqs, setRfqs] = useState([]);
  const [quotations, setQuotations] = useState([]);
  const [approvals, setApprovals] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [error, setError] = useState("");

  useEffect(() => {
    loadReports();
  }, []);

  async function safeGet(url, fallback) {
    try {
      const res = await API.get(url);
      return res.data;
    } catch {
      return fallback;
    }
  }

  async function loadReports() {
    setError("");

    const dashboardData = await safeGet("/dashboard", {
      total_vendors: 0,
      total_rfqs: 0,
      active_rfqs: 0,
      total_quotations: 0,
      approved_quotations: 0,
      total_purchase_orders: 0,
      total_invoices: 0,
      total_spend: 0,
    });

    const vendorData = await safeGet("/vendors", []);
    const rfqData = await safeGet("/rfqs", []);
    const quotationData = await safeGet("/quotations", []);
    const approvalData = await safeGet("/approvals", []);
    const invoiceData = await safeGet("/invoices", []);

    setStats(dashboardData);
    setVendors(vendorData);
    setRfqs(rfqData);
    setQuotations(quotationData);
    setApprovals(approvalData);
    setInvoices(invoiceData);
  }

  function exportReport() {
    const report = `
VendorBridge Procurement Report

Total Vendors: ${stats.total_vendors}
Total RFQs: ${stats.total_rfqs}
Active RFQs: ${stats.active_rfqs}
Total Quotations: ${stats.total_quotations}
Approved Quotations: ${stats.approved_quotations}
Purchase Orders: ${stats.total_purchase_orders}
Invoices: ${stats.total_invoices}
Total Spend: ₹${stats.total_spend}

Generated by VendorBridge ERP
`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "VendorBridge_Report.txt";
    a.click();

    URL.revokeObjectURL(url);
  }

  if (!stats) return <p className="text-white">Loading reports...</p>;

  const spendData = [
    { month: "Jan", spend: 45000 },
    { month: "Feb", spend: 62000 },
    { month: "Mar", spend: 38000 },
    { month: "Apr", spend: 90000 },
    { month: "May", spend: 74000 },
    { month: "Jun", spend: Number(stats.total_spend) || 58000 },
  ];

  const workflowData = [
    { name: "RFQs", value: rfqs.length },
    { name: "Quotes", value: quotations.length },
    { name: "Approvals", value: approvals.length },
    { name: "Invoices", value: invoices.length },
  ];

  const approvalChartData = [
    {
      name: "Approved",
      value: approvals.filter((a) => a.status === "Approved").length,
    },
    {
      name: "Rejected",
      value: approvals.filter((a) => a.status === "Rejected").length,
    },
  ];

  const vendorCategoryMap = vendors.reduce((acc, vendor) => {
    const category = vendor.category || "General";
    acc[category] = (acc[category] || 0) + 1;
    return acc;
  }, {});

  const vendorCategoryData = Object.entries(vendorCategoryMap).map(
    ([name, value]) => ({ name, value })
  );

  const safeVendorCategoryData =
    vendorCategoryData.length > 0
      ? vendorCategoryData
      : [{ name: "No Data", value: 1 }];

  const safeApprovalChartData =
    approvalChartData[0].value + approvalChartData[1].value > 0
      ? approvalChartData
      : [{ name: "No Data", value: 1 }];

  const COLORS = ["#06b6d4", "#8b5cf6", "#22c55e", "#f59e0b", "#ef4444"];

  return (
    <div className="space-y-8">
      {error && (
        <div className="bg-red-500/10 border border-red-500/20 text-red-300 p-4 rounded-2xl">
          {error}
        </div>
      )}

      <motion.div
        initial={{ opacity: 0, y: 22 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-3xl bg-gradient-to-r from-purple-500/20 via-cyan-500/10 to-blue-500/20 border border-white/10 p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-5"
      >
        <div>
          <h1 className="text-4xl font-bold">Reports & Analytics</h1>
          <p className="text-gray-300 mt-3">
            Procurement intelligence, spending insights and vendor performance overview.
          </p>
        </div>

        <button
          onClick={exportReport}
          className="bg-cyan-400 text-black font-semibold px-5 py-3 rounded-xl hover:bg-cyan-300"
        >
          <FaDownload className="inline mr-2" />
          Export Report
        </button>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Kpi title="Total Spend" value={`₹${stats.total_spend}`} icon={<FaRupeeSign />} />
        <Kpi title="Vendors" value={vendors.length} icon={<FaUsers />} />
        <Kpi title="RFQs" value={rfqs.length} icon={<FaChartLine />} />
        <Kpi title="Invoices" value={invoices.length} icon={<FaFileInvoice />} />
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <ChartCard title="Monthly Procurement Spend" subtitle="Spend trend across months" large>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={spendData}>
              <XAxis dataKey="month" stroke="#94a3b8" />
              <YAxis stroke="#94a3b8" />
              <Tooltip contentStyle={tooltipStyle} />
              <Line
                type="monotone"
                dataKey="spend"
                stroke="#06b6d4"
                strokeWidth={4}
                dot={{ r: 5 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Approval Ratio" subtitle="Approved vs rejected">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie data={safeApprovalChartData} dataKey="value" nameKey="name" outerRadius={105} label>
                {safeApprovalChartData.map((entry, index) => (
                  <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip contentStyle={tooltipStyle} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <ChartCard title="Workflow Funnel" subtitle="RFQ to invoice conversion">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={workflowData}>
              <XAxis dataKey="name" stroke="#94a3b8" />
              <YAxis stroke="#94a3b8" />
              <Tooltip contentStyle={tooltipStyle} />
              <Bar dataKey="value" fill="#8b5cf6" radius={[10, 10, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Vendor Categories" subtitle="Vendor distribution" large>
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie data={safeVendorCategoryData} dataKey="value" nameKey="name" outerRadius={110} label>
                {safeVendorCategoryData.map((entry, index) => (
                  <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip contentStyle={tooltipStyle} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="bg-white/10 border border-white/10 rounded-3xl p-6">
        <h2 className="text-2xl font-bold mb-6">Top Vendor Performance</h2>

        <div className="grid gap-4">
          {vendors.length === 0 && (
            <p className="text-gray-400">No vendors found.</p>
          )}

          {vendors.slice(0, 5).map((vendor) => (
            <div
              key={vendor.id}
              className="bg-white/5 border border-white/10 rounded-2xl p-5 flex justify-between items-center"
            >
              <div>
                <h3 className="text-xl font-bold">{vendor.vendor_name}</h3>
                <p className="text-gray-400">{vendor.category}</p>
              </div>

              <div className="text-right">
                <p className="text-yellow-300">⭐ {vendor.rating}</p>
                <p className="text-green-300">{vendor.status}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

const tooltipStyle = {
  background: "#111827",
  border: "1px solid rgba(255,255,255,0.1)",
  borderRadius: "12px",
  color: "white",
};

function Kpi({ title, value, icon }) {
  return (
    <motion.div
      whileHover={{ scale: 1.04, y: -5 }}
      className="bg-gradient-to-br from-cyan-500/20 to-blue-500/10 border border-white/10 rounded-3xl p-6"
    >
      <div className="text-3xl text-cyan-300 mb-4">{icon}</div>
      <p className="text-gray-300">{title}</p>
      <h3 className="text-4xl font-bold text-white mt-2">{value}</h3>
    </motion.div>
  );
}

function ChartCard({ title, subtitle, children, large }) {
  return (
    <div
      className={`bg-white/10 border border-white/10 rounded-3xl p-6 ${
        large ? "xl:col-span-2" : ""
      }`}
    >
      <h2 className="text-2xl font-bold">{title}</h2>
      <p className="text-gray-400 mb-6">{subtitle}</p>
      <div className="h-80">{children}</div>
    </div>
  );
}

export default Reports;